version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - app_network
    env_file:
      - .env
    ports:
      - "3000:3000"

networks:
  app_network:
    driver: bridge
