version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

networks:
  app_network:
    driver: bridge