version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
