FROM node:18-slim

WORKDIR /app

COPY package*.json ./

RUN npm install --only=development

# Install nodemon for development hot-reloading
RUN npm install -g nodemon

COPY . .

EXPOSE 3000

CMD ["nodemon", "app.js"]
